- hosts: localhost
  tasks:
    - name: Download docs archive
      include_role:
        name: download-artifact
      vars:
        download_artifact_job: zuul-tox-docs
        download_artifact_api: "https://zuul.opendev.org/api/tenant/{{ zuul.tenant }}"
        download_artifact_name: docs_archive
        download_artifact_pipeline: gate
    - name: Create working directory
      file:
        path: "{{ zuul.executor.work_root }}/docs"
        state: directory
    - name: Extract docs archive
      unarchive:
        src: "{{ zuul.executor.work_root }}/docs-html.tar.bz2"
        dest: "{{ zuul.executor.work_root }}/docs"
    - name: Write branch marker text
      copy:
        dest: "{{ zuul.executor.work_root }}/docs/.root-marker"
        content: "Project: {{ zuul.project.name }} Branch: {{ zuul.branch }} Build: {{ zuul.build }} Revision: {{ zuul.ref }}"
    - name: Get an AFS token
      include_role:
        name: create-afs-token
    - name: Create publication directory
      file:
        path: "/afs/.openstack.org/project/zuul-ci.org/www/docs/{{ zuul.project.short_name }}/"
        state: directory
    - name: Upload to AFS
      include_role:
        name: upload-afs
      vars:
        afs_source: "{{ zuul.executor.work_root }}/docs/"
        afs_target: "/afs/.openstack.org/project/zuul-ci.org/www/docs/{{ zuul.project.short_name }}"
    - name: Destroy AFS token
      include_role:
        name: destroy-afs-token
