- hosts: localhost
  tasks:
    - name: Write branch marker text
      copy:
        dest: "{{ zuul.executor.log_root }}/docs/.root-marker"
        content: "Project: {{ zuul.project.name }} Branch: {{ zuul.branch }} Build: {{ zuul.build }} Revision: {{ zuul.ref }}"
    - name: Set publication directory to tag
      when: "zuul.tag is defined"
      set_fact:
        publication_dir: "{{ zuul.tag }}"
    - name: Get an AFS token
      include_role:
        name: create-afs-token
    - name: Create publication directory
      file:
        path: "/afs/.openstack.org/project/zuul-ci.org/www/docs/{{ zuul.project.short_name }}/"
        state: directory
    - name: Upload to AFS
      include_role:
        name: upload-afs
      vars:
        afs_source: "{{ zuul.executor.log_root }}/docs/"
        afs_target: "/afs/.openstack.org/project/zuul-ci.org/www/docs/{{ zuul.project.short_name }}"
    - name: Destroy AFS token
      include_role:
        name: destroy-afs-token
